### PR TITLE
feat: Migration to .NET 8

### LINKED ISSUE #562: Migrate from .NET 7.0 to 8.0
[.NET 8](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8/)

image

[Migrate from ASP.NET Core in .NET 7 to .NET 8](https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-7.0&tabs=visual-studio)

image

### PR DESCRIPTION
**Pull request by Jadhielv**
Closes #562

### CODE REVIEW

**Comment by Jadhielv** [comment]
@nminaya please check this PR

**Comment by nminaya** [comment]
@Jadhielv Why not migrating directly to .NET 9?

**Comment by Jadhielv** [comment]
@nminaya Thanks for the suggestion. We'll work on migrating directly to .NET 9 in a future update.

**Review by nminaya — APPROVED** [review]
@Jadhielv I wasn't intending to suggest. It was actually a question out of curiosity.

**Pull request merged**
